name: GitHub Actions Godot build web test
on: [push]
jobs:
  Explore-GitHub-Actions-Godot-Web:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: example
          preset: HTML5
          package: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Result
          path: ~/**/*.zip
